services:
  wrk-wiremock:
    platform: linux/arm64
    image: 'wrk:latest'
    volumes:
      - ./reports/:/home/reports
    scale: 1
    command: # 62504.19 RPS
      - -t50
      - -c200
      - -d30
      - --latency
      - http://wiremock:8080/api/users
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
        reservations:
          cpus: '2'
          memory: 256M
  wrk-toxiproxy: #46798.14
    platform: linux/arm64
    image: 'wrk:latest'
    volumes:
      - ./reports/:/home/reports
    scale: 1
    command:
      - -t50
      - -c3000
      - -d30
      - --latency
      - http://toxiproxy:8081/api/users
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
        reservations:
          cpus: '2'
          memory: 256M
  wrk-app:
    platform: linux/arm64
    image: 'wrk:latest'
    volumes:
      - ./reports/:/home/reports
    command:
      - -t100
      - -c100
      - -d600
      - --latency
#      - http://app:8080/api/v1/accounts-spring-data-cf-then-apply-async-vt/123
#      - http://app:8080/api/v1/accounts-spring-data-cf-then-apply-async-cached-tp/123
#      - http://app:8080/api/v1/accounts-spring-data-cf-then-apply/123
#      - http://app:8080/api/v1/accounts-spring-data-blocking/123

#      - http://app:8080/api/v1/accounts-async-cql-template-before/123
      - http://app:8080/api/v1/accounts-async-cql-template-after/123
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '2'
          memory: 1G
  wrk-app-health:
    platform: linux/arm64
    image: 'wrk:latest'
    volumes:
      - ./reports/:/home/reports
    command:
      - -t100
      - -c2000
      - -d300
      - --latency
      - http://app:8080/actuator/health
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
        reservations:
          cpus: '2'
          memory: 256M
