volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus
    platform: ${CURRENT_PLATFORM}
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/db'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 1024M

  grafana:
    image: grafana/grafana
    platform: ${CURRENT_PLATFORM}
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 512M
