{
 "title": "JVM Overview",
 "description": "Dashboard for Micrometer(Java, Spring Boot, Actuator,prometheus)\nspring boot -->prometheus-->grafana",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, instance)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (process_uptime_seconds{instance=\"$instance\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (process_start_time_seconds{instance=\"$instance\"}*1000)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "File descriptors count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_files_open_files", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})*100/ sum by (service) (jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service)(jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"}) *100/\nsum by (service)(jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Incoming calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rate per endpoint",
   "type": "timeseries",
   "description": "Number of calls per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(service,uri) (rate(http_server_requests_seconds_count{status=~\"2.*.*\"}[$__rate_interval]))",
     "legendFormat": "{{service}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Max latency successful responses",
   "type": "timeseries",
   "description": "Maximum successful response time per endpoint",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"$instance\", status!~\"5..\"}",
     "legendFormat": "{{service}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Average successful response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=\"$instance\", status!~\"5..\"}[$__rate_interval])/\nrate(http_server_requests_seconds_count{instance=\"$instance\", status!~\"5..\"}[$__rate_interval])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Cassandra average latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(s0_cql_requests_seconds_sum[$__rate_interval])/rate(s0_cql_requests_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outgoing calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Rate per endpoint",
   "type": "timeseries",
   "description": "Number of calls per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count[$__rate_interval])",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Http Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_max",
     "legendFormat": "Max"
    },
    {
     "expr": "httpcomponents_httpclient_pool_total_connections",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "httpcomponents_httpclient_pool_route_max_default",
     "legendFormat": "Max per Route"
    }
   ]
  },
  {
   "title": "Average successful response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_sum{instance=\"$instance\", status!~\"5..\"}[$__rate_interval])/\nrate(http_client_requests_seconds_count{instance=\"$instance\", status!~\"5..\"}[$__rate_interval])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Max latency successful responses",
   "type": "timeseries",
   "description": "Maximum successful response time per endpoint",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_client_requests_seconds_max{instance=\"$instance\", status!~\"5..\"}",
     "legendFormat": "{{service}}-{{uri}}"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate all endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(http_server_requests_seconds_count{instance=\"$instance\", status=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(jvm_memory_used_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "{{service}} used"
    },
    {
     "expr": "sum by(service) (jvm_memory_committed_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "{{service}} committed"
    },
    {
     "expr": "sum by (service) (jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "{{service}} max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (jvm_memory_used_bytes{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{service}} used"
    },
    {
     "expr": "sum by(service) (jvm_memory_committed_bytes{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{service}} committed"
    },
    {
     "expr": "sum by(service) (jvm_memory_max_bytes{instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "{{service}} max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (jvm_memory_used_bytes{instance=\"$instance\"})",
     "legendFormat": "{{service}} used"
    },
    {
     "expr": "sum by(service) (jvm_memory_committed_bytes{instance=\"$instance\"})",
     "legendFormat": "{{service}} committed"
    },
    {
     "expr": "sum by(service) (jvm_memory_max_bytes{instance=\"$instance\"})",
     "legendFormat": "{{service}} max"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(system_cpu_usage{instance=\"$instance\"})",
     "legendFormat": "{{service}} system"
    },
    {
     "expr": "(process_cpu_usage{instance=\"$instance\"})",
     "legendFormat": "{{service}} process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{instance=\"$instance\"}[1h])",
     "legendFormat": "{{service}} process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\"}",
     "legendFormat": "{{service}} system-load-1m"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\"}",
     "legendFormat": "{{service}} cpu核数"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{instance=\"$instance\"} or jvm_threads_live_threads{instance=\"$instance\"}",
     "legendFormat": "{{service}} threads-live"
    },
    {
     "expr": "jvm_threads_daemon{instance=\"$instance\"} or jvm_threads_daemon_threads{instance=\"$instance\"}",
     "legendFormat": "{{service}} daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\"} or jvm_threads_peak_threads{instance=\"$instance\"}",
     "legendFormat": "{{service}} peak"
    },
    {
     "expr": "process_threads{instance=\"$instance\"}",
     "legendFormat": "{{service}} process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(service,state) (jvm_threads_states_threads{instance=\"$instance\"})",
     "legendFormat": "{{service}}-{{state}}"
    }
   ]
  },
  {
   "title": "Log Events (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{service}}-{{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "个" }
   ],
   "targets": [
    {
     "expr": "process_files_open{instance=\"$instance\"} or process_files_open_files{instance=\"$instance\"}",
     "legendFormat": "{{service}}-open"
    },
    {
     "expr": "process_files_max{instance=\"$instance\"} or process_files_max_files{instance=\"$instance\"}",
     "legendFormat": "{{service}}-max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 88 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{service}}-used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{service}}-commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "{{service}}-max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{service}}-used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{service}}-commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{service}}-max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by(cause,service,action) (irate(jvm_gc_pause_seconds_count{instance=\"$instance\"}[1m]))",
       "legendFormat": "{{service}}-{{action}}-({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{instance=\"$instance\"}[1m])",
       "legendFormat": "{{service}} {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{instance=\"$instance\"}",
       "legendFormat": "{{service}} {{action}} ({{cause}}) max"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\"}[1m])",
       "legendFormat": "{{service}}allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\"}[1m])",
       "legendFormat": "{{service}}promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{instance=\"$instance\"} or jvm_classes_loaded_classes{instance=\"$instance\"}",
       "legendFormat": "{{service}}-loaded"
      }
     ]
    },
    {
     "title": "Class delta (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{instance=\"$instance\"}[5m])",
       "legendFormat": "{{service}}-delta"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "{{service}}-used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "{{service}}-capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{instance=\"$instance\", id=\"direct\"} or jvm_buffer_count_buffers{instance=\"$instance\", id=\"direct\"}",
       "legendFormat": "{{service}}-count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 120 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "{{service}}-used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "{{service}}-capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{instance=\"$instance\", id=\"mapped\"} or jvm_buffer_count_buffers{instance=\"$instance\", id=\"mapped\"}",
       "legendFormat": "{{service}}-count"
      }
     ]
    }
   ]
  }
 ]
}